services:
  - type: web
    name: emergency-system
    env: python
    plan: free
    autoDeploy: true

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

    envVars:
      - key: BASE_URL
        value: https://your-app-name.onrender.com
      - key: PYTHONUNBUFFERED
        value: "1"
